### ISSUE TITLE
提示user no login

### ISSUE THREAD

**Issue by polarabbit0** [shanmiteko/blive_red_packet#2]
![捕获](https://user-images.githubusercontent.com/86583346/157024254-ccec23e3-0594-43bd-a844-26f3a297c027.PNG)
![捕获1](https://user-images.githubusercontent.com/86583346/157024264-6f5c60f3-85fc-4896-bdcf-816aa567fd9c.PNG)
1.index.js第33行报错，应该加上.toString
2.新建cookie.json输入selenium获取的cookies运行后后仍显示未登录。

**Comment by shanmiteko** [comment]
cookie填写位置和格式是否正确
